<?php

namespace Mobbex\Tests;

use Mobbex\Integrity\Attestation;
use Mobbex\Integrity\Mac;

/**
 * Integrity attestation.
 *
 * The golden vectors are the cross-language contract with the verification service: the same file
 * its Go test consumes, generated by an independent Python implementation
 * written from the spec. A divergence here breaks every merchant at once with a
 * symptom indistinguishable from a real tamper.
 *
 * tests/mac_vectors_runner.php covers the same vectors without PHPUnit, so the
 * PHP 5.6 and 32 bit legs — which PHPUnit 9 cannot run — stay verified too.
 */
class IntegrityTest extends \PHPUnit\Framework\TestCase
{
    /** @var string[] Temporary trees to clean up. */
    protected $trees = [];

    /** @var int Times the URL callable was invoked. */
    public static $urlCalls = 0;

    protected function setUp(): void
    {
        \Mobbex\Platform::$headers  = [];
        \Mobbex\Platform::$domain   = 'tienda.example.com';
        \Mobbex\Platform::$settings = array_merge(\Mobbex\Platform::$settings, [
            'api_key'      => null,
            'access_token' => null,
        ]);

        self::$urlCalls = 0;
    }

    protected function tearDown(): void
    {
        foreach ($this->trees as $tree)
            $this->removeTree($tree);

        $this->trees = [];

        \Mobbex\Platform::$headers = [];
    }

    /**
     * @dataProvider vectorProvider
     */
    public function testGoldenVectors($vector)
    {
        $root = $this->makeTree($vector['disk']);

        $this->assertSame(
            $vector['mac'],
            Mac::computeSpec($vector['prefix'], $vector['nonce'], $vector['platform'], $vector['version'], $vector['spec'], $root),
            'spec MAC diverges from the shared contract'
        );

        // "disk" doubles as the manifest: the global sum covers exactly those
        // paths. On a real install the list arrives as global.files.
        $global = Mac::computeGlobal(
            $vector['prefix'], $vector['nonce'], $vector['platform'], $vector['version'], array_keys($vector['disk']), $root
        );

        $this->assertSame($vector['content_digest'], $global['content_digest'], 'content_digest diverges');
        $this->assertSame($vector['global'], $global['global'], 'global check diverges');
    }

    public function vectorProvider(): array
    {
        $doc   = json_decode(file_get_contents(__DIR__ . '/mac_vectors.json'), true);
        $cases = [];

        foreach ($doc['vectors'] as $vector)
            $cases[$vector['name']] = [$vector];

        return $cases;
    }

    /**
     * A missing file contributes zero bytes rather than raising: a tampered
     * install has to fail verification, not crash the payment.
     */
    public function testMissingFileDoesNotRaise()
    {
        $root = $this->makeTree([]);

        $mac = Mac::computeSpec(
            'MBX-ATTEST-v1',
            str_repeat('00', 32),
            'prestashop',
            '1.0.0',
            [['p' => 'gone.php', 'o' => 0, 'l' => 100]],
            $root
        );

        $this->assertMatchesRegularExpression('/^[0-9a-f]{64}$/', $mac);
    }

    public function testInvalidNonceRaises()
    {
        $this->expectException(\Mobbex\Exception::class);

        Mac::computeSpec('MBX-ATTEST-v1', 'not-hex!', 'prestashop', '1.0.0', [], $this->makeTree([]));
    }

    /**
     * The order the server sent is irrelevant; the path order defines the
     * message. Sorting on our side is what makes that true.
     */
    public function testGlobalIgnoresInputOrder()
    {
        $root = $this->makeTree(['b.txt' => base64_encode('bee'), 'a.txt' => base64_encode('ay')]);

        $one = Mac::computeGlobal('MBX-ATTEST-v1', str_repeat('11', 32), 'prestashop', '1.0.0', ['a.txt', 'b.txt'], $root);
        $two = Mac::computeGlobal('MBX-ATTEST-v1', str_repeat('11', 32), 'prestashop', '1.0.0', ['b.txt', 'a.txt'], $root);

        $this->assertSame($one['global'], $two['global']);
    }

    /**
     * Spec paths are input from outside. One escaping the install directory
     * would make the plugin hash files it has no business reading, and that hash
     * travels back to us — a compromised endpoint would become a slow
     * exfiltration primitive. A refused path contributes zero bytes, like a
     * missing file, so the value simply fails to match.
     */
    public function testPathTraversalIsRefused()
    {
        $root   = $this->makeTree(['ok.txt' => base64_encode('fine')]);
        $nonce  = str_repeat('22', 32);
        $secret = dirname($root) . '/mbx-outside-' . uniqid('', true);

        file_put_contents($secret, 'contenido fuera del modulo');

        $escape  = '../' . basename($secret);
        $refused = Mac::computeSpec('MBX-ATTEST-v1', $nonce, 'p', '1.0.0', [['p' => $escape, 'o' => 0, 'l' => 0]], $root);
        $missing = Mac::computeSpec('MBX-ATTEST-v1', $nonce, 'p', '1.0.0', [['p' => $escape, 'o' => 0, 'l' => 0]], $root . '/nope');

        unlink($secret);

        // Identical means the file outside was never read: both contributed zero
        // bytes, and only the path string entered the message.
        $this->assertSame($missing, $refused, 'a traversal path must read nothing');

        foreach (['/etc/passwd', 'a/../../b', 'C:\\windows\\win.ini', '..\\..\\x'] as $bad)
            $this->assertFalse($this->isSafe($bad), "must refuse $bad");

        foreach (['ok.txt', 'nested/deep/file.php', 'vendor/mobbexco/php-plugins-sdk/src/Api.php'] as $good)
            $this->assertTrue($this->isSafe($good), "must accept $good");
    }

    /**
     * @param string $path
     *
     * @return bool
     */
    protected function isSafe($path)
    {
        $method = new \ReflectionMethod('Mobbex\Integrity\Mac', 'isSafePath');

        if (PHP_VERSION_ID < 80100)
            $method->setAccessible(true);

        return $method->invoke(null, $path);
    }

    public function testHeaderProviderIsRegisteredOnceOnly()
    {
        Attestation::init('prestashop', __DIR__, '1.0.0');
        Attestation::init('prestashop', __DIR__, '1.0.0');

        $this->assertCount(1, \Mobbex\Platform::$headers);
    }

    /**
     * Only checkout and subscriber creation are attested. Attesting every call
     * would multiply the cost for nothing, and the challenge request itself
     * must never be.
     */
    public function testOnlyChecksoutRequestsAreAttested()
    {
        Attestation::init('prestashop', __DIR__, '1.0.0');

        $this->assertSame([], Attestation::getHeaders(['uri' => 'sources']));
        $this->assertSame([], Attestation::getHeaders([]));
    }

    /**
     * Mobbex\Modules\Subscriber posts to subscriptions/{uid}/subscriber/{uid}.
     * That exact call must attest, same as checkout, since it also provisions
     * a paying object.
     */
    public function testSubscriberCreationIsAttested()
    {
        Attestation::init('prestashop', __DIR__, '1.0.0');

        $headers = Attestation::getHeaders([
            'method' => 'POST',
            'uri'    => 'subscriptions/sub1/subscriber/usr1',
        ]);

        $this->assertContains('x-integrity-mode: static', $headers);
    }

    /**
     * Everything else in the subscription domain shares the same URI prefix,
     * and one case — reading a subscriber's executions — shares the exact same
     * URI as creation, differing only by verb. None of these may attest: the
     * pattern must stay anchored to the literal create call, not just "smells
     * like a subscriber URI".
     *
     * @dataProvider subscriptionUrisNotInScopeProvider
     */
    public function testOtherSubscriptionRequestsAreNotAttested($data)
    {
        Attestation::init('prestashop', __DIR__, '1.0.0');

        $this->assertSame([], Attestation::getHeaders($data));
    }

    public function subscriptionUrisNotInScopeProvider(): array
    {
        return [
            'search_execution (same URI, GET)'  => [['method' => 'GET',  'uri' => 'subscriptions/sub1/subscriber/usr1']],
            'execute_charge'                     => [['method' => 'POST', 'uri' => 'subscriptions/sub1/subscriber/usr1/execution']],
            'activate/suspend action'            => [['method' => 'POST', 'uri' => 'subscriptions/sub1/subscriber/usr1/action/activate']],
            'retry_charge action'                => [['method' => 'GET',  'uri' => 'subscriptions/sub1/subscriber/usr1/execution/eid1/action/retry']],
            'search_subscriber (query string)'   => [['method' => 'GET',  'uri' => 'subscriptions/sub1/subscriber?page=0&search=x']],
            // Same URI shape as modify_subscription: creating or updating the
            // subscription itself is out of scope for this fix.
            'subscription creation/modification' => [['method' => 'POST', 'uri' => 'subscriptions/sub1']],
        ];
    }

    /**
     * Without credentials no challenge can be fetched, and the result must be a
     * degraded marker rather than an exception or a missing header set: an
     * attestation failure may never break a payment.
     */
    public function testDegradesWhenChallengeIsUnavailable()
    {
        Attestation::init('prestashop', __DIR__, '1.0.0');

        $headers = Attestation::getHeaders(['uri' => 'checkout']);

        $this->assertContains('x-integrity-mode: static', $headers);
        $this->assertContains('x-integrity-platform: prestashop', $headers);
        $this->assertContains('x-integrity-version: 1.0.0', $headers);

        foreach ($headers as $header)
            $this->assertStringNotContainsString("\n", $header, 'headers must never carry a newline');
    }

    /**
     * The successful path: the headers a real checkout carries, with values
     * cross-checked against the shared golden vector rather than against this
     * implementation. Reaching it without a network call is why headersFor() is
     * split out of getHeaders().
     */
    public function testAttestedHeadersMatchTheGoldenVector()
    {
        $doc    = json_decode(file_get_contents(__DIR__ . '/mac_vectors.json'), true);
        $vector = null;

        foreach ($doc['vectors'] as $candidate) {
            if ($candidate['name'] === 'multi-archivo-en-orden')
                $vector = $candidate;
        }

        $root = $this->makeTree($vector['disk']);

        Attestation::init($vector['platform'], $root, $vector['version']);

        $headers = Attestation::headersFor([
            'id'          => 'chg_test',
            'nonce'       => $vector['nonce'],
            'files'       => $vector['spec'],
            'globalFiles' => array_keys($vector['disk']),
        ]);

        $this->assertSame([
            'x-integrity-mode: challenge',
            'x-integrity-challenge: chg_test',
            'x-integrity-mac: ' . $vector['mac'],
            'x-integrity-platform: ' . $vector['platform'],
            'x-integrity-version: ' . $vector['version'],
            'x-integrity-url: https://tienda.example.com',
            'x-integrity-global: ' . $vector['global'],
        ], $headers);
    }

    /**
     * The shop URL: a string that is also a callable — 'wc_get_checkout_url' is
     * the natural WooCommerce value — has to be invoked, not sent literally.
     * Checking is_callable() before treating the value as a string is what
     * decides that, and no URL can be mistaken for a callable.
     */
    public function testShopUrlAcceptsStringCallableAndNull()
    {
        $cases = [
            // value                                      expected header value
            [null,                                        'https://tienda.example.com'],
            ['https://shop.test/checkout',                'https://shop.test/checkout'],
            ['Mobbex\Tests\mbxTestCheckoutUrl',           'https://desde-callable.test/pay'],
            [function () { return 'https://cb.test/x'; }, 'https://cb.test/x'],
            // A callable that cannot work it out — no context, a cron, the back
            // office — falls back to the host rather than sending nothing.
            [function () { return null; },                'https://tienda.example.com'],
        ];

        foreach ($cases as $case) {
            list($value, $expected) = $case;

            Attestation::init('prestashop', __DIR__, '1.0.0', $value);

            $this->assertContains(
                'x-integrity-url: ' . $expected,
                Attestation::getHeaders(['uri' => 'checkout']),
                'failed for ' . var_export($value, true)
            );
        }
    }

    /**
     * @dataProvider badUrlProvider
     */
    public function testRejectedUrlsAreOmittedNeverMangled($url, $why)
    {
        Attestation::init('prestashop', __DIR__, '1.0.0', $url);

        foreach (Attestation::getHeaders(['uri' => 'checkout']) as $header)
            $this->assertStringNotContainsString('x-integrity-url', $header, $why);
    }

    public function badUrlProvider(): array
    {
        return [
            'non-ascii host'   => ['https://tiendañ.com/pedido', 'stripping the ñ yields tienda.com, a different real site'],
            'non-ascii path'   => ['https://shop.test/pédido', 'a mangled path is valid and wrong'],
            'javascript'       => ['javascript:alert(1)', 'only http and https may travel'],
            'file'             => ['file:///etc/passwd', 'only http and https may travel'],
            'crlf'             => ["https://shop.test/a\r\nx-evil: yes", 'a newline would inject a header'],
            'too long'         => ['https://shop.test/' . str_repeat('a', 600), 'past the cap it is dropped, not cut'],
            'bare word'        => ['checkout', 'without a scheme it would become https://checkout, which validates'],
            'undefined fn'     => ['wc_get_checkout_url_undefined', 'a callable name that resolves to nothing is not a URL'],
            'schemeless host'  => ['shop.test/order', 'only the host fallback may go schemeless'],
        ];
    }

    /**
     * An empty value is "I don't know", not "here is a bad URL", so it takes the
     * host fallback rather than being dropped.
     */
    public function testEmptyValueFallsBackToTheHost()
    {
        Attestation::init('prestashop', __DIR__, '1.0.0', '');

        $this->assertContains('x-integrity-url: https://tienda.example.com', Attestation::getHeaders(['uri' => 'checkout']));
    }

    public function testQueryStringAndFragmentAreStripped()
    {
        Attestation::init('prestashop', __DIR__, '1.0.0', 'https://shop.test/order?cart=abc123&token=s3cr3t#step2');

        $this->assertContains('x-integrity-url: https://shop.test/order', Attestation::getHeaders(['uri' => 'checkout']));
    }

    /**
     * The one that proves the exception is not re-thrown from inside the catch
     * block: degraded() also wants the URL, and asking again would raise inside
     * an exception handler and escape getHeaders().
     */
    public function testThrowingCallableOmitsTheUrlAndKeepsTheRest()
    {
        Attestation::init('prestashop', __DIR__, '1.0.0', function () {
            self::$urlCalls++;
            throw new \RuntimeException('no context');
        });

        $headers = Attestation::getHeaders(['uri' => 'checkout']);

        $this->assertContains('x-integrity-mode: static', $headers);
        $this->assertContains('x-integrity-platform: prestashop', $headers);

        foreach ($headers as $header)
            $this->assertStringNotContainsString('x-integrity-url', $header);

        // Resolved once and the failure cached, so degraded() did not call again.
        $this->assertSame(1, self::$urlCalls);
    }

    /**
     * Resolving is deferred to the moment the headers are emitted, and it does
     * not happen at all on a request that is not a checkout.
     */
    public function testCallableIsNotInvokedOutsideCheckout()
    {
        Attestation::init('prestashop', __DIR__, '1.0.0', function () {
            self::$urlCalls++;

            return 'https://shop.test/checkout';
        });

        $this->assertSame(0, self::$urlCalls, 'init() must not resolve the URL');

        Attestation::getHeaders(['uri' => 'sources']);

        $this->assertSame(0, self::$urlCalls, 'a non-checkout request must not resolve it');

        Attestation::getHeaders(['uri' => 'checkout']);
        Attestation::getHeaders(['uri' => 'checkout']);

        $this->assertSame(1, self::$urlCalls, 'resolved at most once per request');
    }

    public function testDegradedModeCarriesTheUrl()
    {
        Attestation::init('prestashop', __DIR__, '1.0.0', 'https://shop.test/order');

        // No credentials, so the challenge cannot be fetched and this degrades.
        $this->assertContains('x-integrity-url: https://shop.test/order', Attestation::getHeaders(['uri' => 'checkout']));
    }

    /**
     * A crafted challenge id must not be able to inject headers of its own.
     */
    public function testChallengeIdCannotInjectHeaders()
    {
        Attestation::init('prestashop', $this->makeTree([]), '1.0.0');

        $headers = Attestation::headersFor([
            'id'          => "abc\r\nx-evil: yes",
            'nonce'       => str_repeat('00', 32),
            'files'       => [],
            'globalFiles' => [],
        ]);

        $this->assertSame('x-integrity-challenge: abcx-evil: yes', $headers[1]);

        foreach ($headers as $header) {
            $this->assertStringNotContainsString("\r", $header);
            $this->assertStringNotContainsString("\n", $header);
        }
    }

    /**
     * A provider that blows up must be skipped, never propagated: it runs inside
     * the request path.
     */
    public function testApiHeadersSurviveAFailingProvider()
    {
        \Mobbex\Platform::addHeaderProvider(function ($data) {
            throw new \Exception('boom');
        });

        \Mobbex\Platform::addHeaderProvider(function ($data) {
            return ['x-test: ' . $data['uri']];
        });

        $method = new \ReflectionMethod('Mobbex\Api', 'getHeaders');

        if (PHP_VERSION_ID < 80100)
            $method->setAccessible(true);

        $headers = $method->invoke(null, ['uri' => 'checkout']);

        $this->assertContains('x-test: checkout', $headers);
        $this->assertContains('content-type: application/json', $headers);
    }

    /**
     * @param array $disk Map of relative path => base64 content.
     *
     * @return string
     */
    protected function makeTree($disk)
    {
        $root = sys_get_temp_dir() . '/mbx-integrity-' . uniqid('', true);

        mkdir($root, 0777, true);

        foreach ($disk as $path => $base64) {
            $target = $root . '/' . $path;

            if (!is_dir(dirname($target)))
                mkdir(dirname($target), 0777, true);

            file_put_contents($target, base64_decode($base64));
        }

        $this->trees[] = $root;

        return $root;
    }

    /**
     * @param string $path
     *
     * @return void
     */
    protected function removeTree($path)
    {
        if (!is_dir($path))
            return;

        foreach (scandir($path) as $entry) {
            if ($entry === '.' || $entry === '..')
                continue;

            $child = $path . '/' . $entry;

            is_dir($child) ? $this->removeTree($child) : unlink($child);
        }

        rmdir($path);
    }
}

/**
 * Named function used to prove that a string which is also a callable gets
 * invoked instead of being sent as a literal URL — the WooCommerce shape.
 *
 * @return string
 */
function mbxTestCheckoutUrl()
{
    return 'https://desde-callable.test/pay';
}
