name: CI

on: [push]

jobs:
  check-syntax:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [5.6, 7.0, 7.4, 8.0, 8.2]

    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP with tools
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer
    - name: Install dependencies
      run: composer install --no-dev
    - name: Intall PHPCS and code standard
      run: composer global require "phpcompatibility/php-compatibility" "squizlabs/php_codesniffer=*"
    - name: Configure standard
      run: ~/.composer/vendor/bin/phpcs --config-set installed_paths ~/.composer/vendor/phpcompatibility/php-compatibility
    - name: Log that standards are installed
      run: ~/.composer/vendor/bin/phpcs -i
    - name: Execute PHPCS
      run: ~/.composer/vendor/bin/phpcs -p . --standard=PHPCompatibility

  run-tests:
    needs: check-syntax
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install dependencies
      run: composer install --dev
    - name: Run test suite
      run: composer run-script test